### ISSUE TITLE
Root instead Vagrant on mounted folder

### ISSUE THREAD

**Issue by gotlium** [fgrehm/vagrant-lxc#389]
Parallels and Vagrant provider user:

	vagrant@vagrant:/vagrant$ ls -l
	-rw-r--r-- 1 vagrant vagrant 3.2K Sep 14 20:25 Vagrantfile

Lxc provider:
	vagrant@vagrant:/vagrant$ ls -l
	-rw-r--r--  1 root root  3042 Sep 14 17:26 Vagrantfile

**Comment by fgrehm** [comment]
Based on the other issues you've created I'm assuming that your user on the host is `root` and because of the way "synced folders" (currently) works, the directories inside the container will have the same ownership as outside.

The reason why that dir gets the `vagrant` ownership on other providers is because (at least for virtualbox) there is a way to specify [a mapping](https://github.com/mitchellh/vagrant/blob/92e6062f8dbb461c8b0f0a3e59c6427385851083/plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb#L11-L33) between owners at the file system level and (AFAIK) there is no easy way to do that with vagrant-lxc bind mounts.

Sorry but I don't think there's much we can do here. If someone knows how to work around that (besides using `rsync` synced folders or manually `chown`ing dirs) please let us know!
