### ISSUE TITLE
State of the project?

### ISSUE THREAD

**Issue by guettli** [fgrehm/vagrant-lxc#492]
There was no update since two years.

What is the state of the project?

Are there better ways to get light-weight virtualization provider for vagrant?

**Comment by fgrehm** [comment]
Hi there!

> What is the state of the project?

@hsoft was helping out but he also ended up stepping down [a while ago](https://github.com/fgrehm/vagrant-lxc/issues/375#issuecomment-453134331). I personally don't use this project anymore and usually just go with docker / docker-compose as needed.

> Are there better ways to get light-weight virtualization provider for vagrant?

Sorry, no idea, it's been a while since I had to use vagrant :sweat_smile:
